module.exports = Object.freeze({
    PUBLICKEY_CONSTANT: `-----BEGIN PUBLIC KEY-----
    MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAM75rfwLKFI4zA5MtlFfTf0PVRX4UpCC
    A+ridiLmx4UjvNS9LbQJNV4qLpRMgSUx18jXNk/4bp6TDsvGbiEW1c0CAwEAAQ==
    -----END PUBLIC KEY-----`,
    PRIVATEKEY_CONSTANT: `-----BEGIN PRIVATE KEY-----
    MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAzvmt/AsoUjjMDky2
    UV9N/Q9VFfhSkIID6uJ2IubHhSO81L0ttAk1XioulEyBJTHXyNc2T/hunpMOy8Zu
    IRbVzQIDAQABAkA6GbKyZvtpoVH+zZ/8VbGR0SUEZtHeiPDKlcmt4HSvtagroW3w
    MzuTkSGcrvK9sFglw50bG7rsxWQD3FMBgUihAiEA79QcRPZRdORWFALwa9DBeEAW
    yp/+3sKQ+xaOvGEUxQkCIQDc7nXx1Tt2oU9yVZJcbZ/eUKmPQkFA0D7K3yPBa8nf
    pQIhALaFkmI1qHay1IP0XK9hN+zhsbbSH3G/WAGQAF+D7v+pAiEAxlk4frNnvWu5
    ffahfmXVP6y/biSXnO7ZUR3gZgi1pxkCIEOBdzhPt/ajfdaDpiX04f637PGB1ySr
    PvfBwagPKuUc
    -----END PRIVATE KEY-----`
});