module.exports = Object.freeze({
    PUBLICKEY_CONSTANT: `-----BEGIN PUBLIC KEY-----
    MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ+fLYBQ9RS2Tz8kbJkbEng6SeF2jT/x
    dz9qPIaN3nDLtnZ0g4uqiNXKoc49L1FSnQQ9Q1Jc9gF7+oJcGZab2gcCAwEAAQ==
    -----END PUBLIC KEY-----`,
    PRIVATEKEY_CONSTANT: `-----BEGIN PRIVATE KEY-----
    MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAn58tgFD1FLZPPyRs
    mRsSeDpJ4XaNP/F3P2o8ho3ecMu2dnSDi6qI1cqhzj0vUVKdBD1DUlz2AXv6glwZ
    lpvaBwIDAQABAkANFsJmaT0Pi7uH0/bLvzqOfUkdodkHS0eZ/Z4k8nExEoIgjyGt
    MvLTudyLq2ZOqXbhZ2+vHGryroOEHuTfUNLRAiEA0gshx5jznwcJQgWj//rGmbG9
    keEb3fYX2cGRQH3sdw0CIQDCi9jF1z72cmcKugYtz44he4vufJZEAizcIDynEV0Q
    YwIgUapkWt+cMUOiFNpullNhrlZOF48Hr7hEM7UwDXwoWW0CIQCgyqDRc4OQgSF1
    FicBOeiI9+nBpKs1bm7RSLuYgZtfbQIhAKqGbPxdUlGZLMyvkgj1PMwfoTV2UTn6
    dRHOZ7C6O7cx
    -----END PRIVATE KEY-----`
});